name: My First Workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5
        - name: List and Read
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f elephant "Run for cover, I am king of Jungle" >> elephant.txt
        # - name: Welcome message 
        #   run: echo "My first Github Actions Job" 
        
        # - name: List Files
        #   run: ls

        # - name: Read the file
        #   run: cat README.md
