name: Exploring Variables and Secrets

on:
  workflow_dispatch: 
  schedule:
    - cron: "*/1 * * * *"   
#   push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx   

jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Docker Build
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME

        - name: Docker login
          run: echo docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
    deploy:
      concurrency: 
        group: production-deployment
        cancel-in-progress: false
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        run: |
          echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 120